name: Docker (build & push)

on:
  push:
    branches:
      - main
    paths:
      - 'test-suite/**'

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:test-suite'
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-test-suite:latest
