name: Docker (build & push)

on:
  push:
    branches:
      - main
    paths:
      - 'test-suite/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:test-suite'
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-test-suite:latest
